export default [
    {
        'avatar': '../images/avatar-mark-webber.webp',
        'name': 'Mark Webber',
        'activity': 'reacted to your recent post',
        'relationType': 'post',
        'relation': 'My first tournament today!',
        'read': false,
        'time': '1m ago',
    },
    {
        'avatar': '../images/avatar-angela-gray.webp',
        'name': 'Angela Gray',
        'activity': 'followed you',
        'relationType': null,
        'relation': null,
        'read': false,
        'time': '5m ago',
    },
    {
        'avatar': '../images/avatar-jacob-thompson.webp',
        'name': 'Jacob Thompson',
        'activity': 'has joined your group',
        'relationType': 'post',
        'relation': 'Chess Club',
        'read': false,
        'time': '1 day ago',
    },
    {
        'avatar': '../images/avatar-rizky-hasanuddin.webp',
        'name': 'Rizky Hasanuddin',
        'activity': 'sent you a private message',
        'relationType': null,
        'relation': null,
        'read': true,
        'time': '5 days ago',
        'message': "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    },
    {
        'avatar': '../images/avatar-kimberly-smith.webp',
        'name': 'Kimberly Smith',
        'activity': 'commented on your picture',
        'relationType': 'picture',
        'relation': '../images/image-chess.webp',
        'read': true,
        'time': '1 week ago',
    },
    {
        'avatar': '../images/avatar-nathan-peterson.webp',
        'name': 'Nathan Peterson',
        'activity': 'reacted to your recent post',
        'relationType': 'post',
        'relation': '5 end-game strategies to increase your win rate',
        'read': true,
        'time': '2 week ago',
    },
    {
        'avatar': '../images/avatar-anna-kim.webp',
        'name': 'Anna Kim',
        'activity': 'left the group',
        'relationType': 'post',
        'relation': 'Chess Club',
        'read': true,
        'time': '2 weeks ago',
    },
]
